const productos = [
    {
        id:1,
        nombre:"3060",
        desc:"grafica",
        precio:90000,
        img:"src/img/goku2.jpg",
        cantidad:1,
    },
    {
        id:2,
        nombre:"3070",
        desc:"grafica",
        precio:1500,
        img:"src/img/krilingoku2.jpg",
        cantidad:1,
    },
    {
        id:3,
        nombre:"3080",
        desc:"grafica",
        precio:90000,
        img:"src/img/krilingoku3.jpg",
        cantidad:1,
    },
    {
        id:4,
        nombre:"6700 tx",
        desc:"grafica",
        precio:90000,
        img:"src/img/krilingoku4.jpg",
        cantidad:1,
    },
]